### ISSUE TITLE
Flipper not shows installed plugins

### ISSUE THREAD

**Issue by TheEhsanSarshar** [facebook/flipper#1254]
## 🐛 Bug Report
  I am using react native 0.62 with flipper
  I have recently installed Reactoron and redux-debugger 
  but plugins not listed in side bar

## To Reproduce
![Screen Shot 2020-06-14 at 12 32 01 PM](https://user-images.githubusercontent.com/46188784/84588258-2a0cb200-ae3b-11ea-983a-6224723eafb8.png)

![Screen Shot 2020-06-14 at 12 33 23 PM](https://user-images.githubusercontent.com/46188784/84588269-490b4400-ae3b-11ea-9c0d-fcaf1670c569.png)

## Environment
react-native 0.62
flipper 0.46.0

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 109.01 MB / 8.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.11.0 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2

**Comment by whenmoon** [comment]
I have a very similar problem https://github.com/facebook/flipper/issues/1253

**Comment by EhsanSarshar** [comment]
@whenmoon I am trying stuff on this link may it help 
https://fbflipper.com/docs/troubleshooting/#no-plugins-showing-up-for-your-device

**Comment by mweststrate** [comment]
@EhsanSarshar did you install `react-native-flipper` as well?

**Comment by EhsanSarshar** [comment]
@mweststrate other part of flipper like React devtools and other logging part work correctly

**Comment by mweststrate** [comment]
@EhsanSarshar we've just published a troubleshooting guide: https://fbflipper.com/docs/troubleshooting#react-native. Would mind to follow it and report back on any specific issues that fail?

**Comment by EhsanSarshar** [comment]
@mweststrate   :(  still the same issue.
is there any way to see through the log files of flipper do it have any log kind of things

**Comment by mweststrate** [comment]
@EhsanSarshar Flipper errors should be logged into the device logs under SM-M307FN. It really looks that the Flipper client isn't initialized at all. Or if there is an error in Flipper itself it should show up in View > Developer Tools > console. 

Are you sure you are using a debug build and ticked all the bullets on the trouble shooting page, including verifying your files look similar to the ones suggested by by the upgrade tool? Otherwise consider creating a stripped down version of your app public, it really looks like one of the steps missed since the app is completely absent.

**Comment by EhsanSarshar** [comment]
@mweststrate as it seems the problem is with wrong react native upgrade steps. but as I fix it by following exactly the steps in [here](https://react-native-community.github.io/upgrade-helper/?from=0.61.4&to=0.62.2). but still plugins not showing and flipper can't connect to my app. is there any way to see through logs to spot the issue

**Comment by jknoxville** [comment]
You may also find the diagnostic screen helpful, it will shed light on where the connection is failing: https://fbflipper.com/docs/troubleshooting/#android

**Comment by bizzguy** [comment]
@EhsanSarshar   Your post contains a very comprehensive list of environment information.  I was wondering how you produced it.  Is there a script?

**Comment by EhsanSarshar** [comment]
@bizzguy react-native info

**Comment by EhsanSarshar** [comment]
@jknoxville I am trying the command but as the Docs said "This will only work if you added FlipperDiagnosticActivity to your AndroidManifest.xml. See [getting started for help](https://fbflipper.com/docs/troubleshooting/getting-started/index)." but getting started page not exist . 404

**Comment by bizzguy** [comment]
@EhsanSarshar  I'm an Android native app developer which may be why I didn't understand your answer.  Is that a command line thing in React Native?  Not sure how I would run that command.

**Comment by jknoxville** [comment]
@EhsanSarshar thanks, I'll fix that link. This is where it's supposed to be pointing: https://fbflipper.com/docs/getting-started/android-native#diagnostics

**Comment by EhsanSarshar** [comment]
> @EhsanSarshar I'm an Android native app developer which may be why I didn't understand your answer. Is that a command line thing in React Native? Not sure how I would run that command.

yeah

**Comment by mweststrate** [comment]
@EhsanSarshar was this issue fixed or is it still open?

**Comment by snaik2064** [comment]
@EhsanSarshar  I was having same problem with Flipper version 0.55 for redux-debugger & async storage plugin.

**1.** The main problem, I was expecting plugin to show up in flipper only by installing it through **"Manage plugins"** in Flipper.

**2.** _But not only you have to install **react-native-flipper** you also have to install the respective **"react native"** package in your react native app._

**3.** As mentioned in official docs Troubleshooting Issues: 
https://fbflipper.com/docs/troubleshooting/#q-i-see-my-app-but-i-dont-see-the-external-plugins-ive-installed
Make sure you've installed the app part of the plugin. Typically the installation instructions of the plugin itself need to be followed here.  

**4.** For your redux-debugger plugin
 Install **redux-flipper** & **react-native-flipper** in react native app.

**5.** Here is the complete doc and installation steps.
https://classic.yarnpkg.com/en/package/flipper-plugin-redux-debugger

**P.S.** Always click the info icon in plugin to get the detailed doc of required dependencies & installation process.

![plugin info](https://user-images.githubusercontent.com/22753888/92313032-5d974c80-efe4-11ea-8ed8-06e7d30e5c6d.png)
![redux dev tool](https://user-images.githubusercontent.com/22753888/92313033-5ec87980-efe4-11ea-80ff-1e89c0ac7f38.png)

**Comment by EhsanSarshar** [comment]
@snaik2064 not work :(

**Comment by snaik2064** [comment]
@EhsanSarshar  for **redux-flipper** have you followed this steps:

https://classic.yarnpkg.com/en/package/flipper-plugin-redux-debugger

**Comment by AbdelkhalekESI** [comment]
Hi, I'm facing the same issue with a physical android device ( Pixel 3 ).
- I can see react-native logs. 
- react-native version 0.62.2.
- My app is ejected from expo.

**Comment by adi2412** [comment]
For anyone facing this issue with an iOS Swift project, the problem is in the Build Settings OTHER_SWIFT_FLAGS added automatically. Search for "Other Swift Flags" under "Swift Compiler - Custom Flags" and under the Debug configuration, you should see two keys added "-Xcc" immediately followed by "-DFB_SONARKIT_ENABLED=1". Remove both of them, and add a single key with the value "-DFB_SONARKIT_ENABLED"

<img width="991" alt="Screenshot 2020-10-12 at 8 23 33 PM" src="https://user-images.githubusercontent.com/2319795/95760770-0cf0ce80-0cc9-11eb-9826-b16c03728447.png">
