### ISSUE TITLE
Android Sample App Post Request failing with 404 error

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#1480]
## 🐛 Bug Report

The Android Sample app allows user to "Send POST Request" which can be used to demonstrate the Network Plugin.  However, the request is no longer working.  It fails with a 404 (Page Not Found) error.  It appears the the service used to host the request (mockable.io) is no longer configured correctly.

## To Reproduce

1) Start Flipper
2) Start the Android Sample App
3) Issue the post request from the Sample App

![image](https://user-images.githubusercontent.com/337874/90540929-81831300-e147-11ea-8958-50d99585f330.png)

4) The request never completes in Flipper

![image](https://user-images.githubusercontent.com/337874/90541042-aa0b0d00-e147-11ea-9cfa-fe73c5aca8be.png)

Note:  Here is the code that makes the request:

![image](https://user-images.githubusercontent.com/337874/90541074-b7c09280-e147-11ea-8d19-87f33d14322b.png)

## Environment

Flipper 0.52.1

**Comment by bizzguy** [comment]
@mweststrate 
Could you add the "plugin-network" label to this issue?  I could not figure out how to do it myself.  I'm assuming that I don't have access.  

Thanks.

**Comment by mweststrate** [comment]
Done. P.s. I think it is pretty irrelevant for the demo where it posts to, so any other demo endpoint like for example the star wars api will probably do.

**Comment by bizzguy** [comment]
@mweststrate I agree.  It would be nice to have both GET and POST, something with a bunch of headers and a fairly complex JSON response.  And something that is pretty stable.  I'll do some research.  I also noticed that the sample app for iOS has 3 requests while Android has 2.  Probably good to normalize that as well.

**Comment by bizzguy** [comment]
This is still an issue but I do not have the permissions to change the label.
