### ISSUE TITLE
Flipper 0.96.0 pods issue

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [facebook/flipper#2543]
I get this after i do `cd ios & pod install --repo-update`

[!] CocoaPods could not find compatible versions for pod "FlipperKit/FKPortForwarding":
  In Podfile:
    FlipperKit/FKPortForwarding (= 0.96.0)

None of your spec sources contain a spec satisfying the dependency: `FlipperKit/FKPortForwarding (= 0.96.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by nikoant** [comment]
That's probably because we just released 0.96.0 few hours ago and podspec update has not been merged yet.

**Comment by skurgansky-sugarcrm** [comment]
@nikoant could you tell pls how long will it take ? Now this error is still present

**Comment by nikoant** [comment]
Could you test now please?

**Comment by skurgansky-sugarcrm** [comment]
@nikoant results 
`cd ios`
`pod repo update`
```
Updating spec repo `master`
  $ /usr/bin/git -C /Users/ksv/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 2604, done.        
  remote: Counting objects: 100% (2604/2604), done.        
  remote: Compressing objects: 100% (1610/1610), done.        
  remote: Total 2604 (delta 1547), reused 1936 (delta 916), pack-reused 0        
  Receiving objects: 100% (2604/2604), 400.56 KiB | 699.00 KiB/s, done.
  Resolving deltas: 100% (1547/1547), completed with 400 local objects.
  From https://github.com/CocoaPods/Specs
     a7cb8e86bfdb..fa4694eacf19  master     -> origin/master
  $ /usr/bin/git -C /Users/ksv/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/ksv/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at fa4694eacf19 [Add] IMQAMPMAgent 3.1.11
Updating spec repo `trunk`
```

`pod install --repo-update`
```Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
  In snapshot (Podfile.lock):
    Flipper-Folly (= 2.5.3, ~> 2.5)

  In Podfile:
    Flipper (= 0.96.0) was resolved to 0.96.0, which depends on
      Flipper-Folly (~> 2.6)

    Flipper-Folly (~> 2.5.3)

Specs satisfying the `Flipper-Folly (~> 2.5.3), Flipper-Folly (= 2.5.3, ~> 2.5), Flipper-Folly (~> 2.6)` dependency were found, but they required a higher minimum deployment target.```

**Comment by mweststrate** [comment]
Probably you have custom version overrides in your podfile, can you remove
those?

**Comment by skurgansky-sugarcrm** [comment]
I use clean RN project example app. 

this is the code of pod file. Just like it's said to be on this page https://fbflipper.com/docs/getting-started/react-native

```
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # use_flipper!()
  use_flipper!({ 'Flipper' => '0.96.0' })
```

**Comment by b3coded** [comment]
@skurgansky-sugarcrm try this one
```rb
use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
```

**Comment by skurgansky-sugarcrm** [comment]
> @skurgansky-sugarcrm try this one
> 
> ```ruby
> use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
> ```

`pod install` passed. thanks 👍

**Comment by skurgansky-sugarcrm** [comment]
should I use the latest Flipper pods btw? I have errors while installing dependencies all the time

**Comment by shamilovtim** [comment]
0.100.0, dependencies still haven't been fixed for this package

**Comment by skurgansky-sugarcrm** [comment]
I have managed to install them with this:
`use_flipper!({ 'Flipper-Folly' => '2.6.9', 'Flipper' => '0.100.0' })`
But still it doesn't work properly.. Hermes debugger can not connect to metro

**Comment by mweststrate** [comment]
Closing this issue as it based on old versions. Please refer to the Podfile of https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample for a list of deps that should work correctly. Note that you can use this one generally as reference point, as that is the one we verify of that it is working correctly.
