### ISSUE TITLE
"NO APPLICATION SELECTED" issue with Flipper

### ISSUE THREAD

**Issue by realtril** [facebook/flipper#3027]
I have managed to connect a device ( I see logs and see the tree of React Native elements), but now I have an issue with connecting the app - "NO APPLICATION SELECTED" is what I see. Any ideas to fix it?

Using react native 0.64.2/ tried 0.66.1 as well.

<img width="614" alt="Screen Shot 2021-11-05 at 1 17 48 PM" src="https://user-images.githubusercontent.com/53015418/140504076-d740378e-052b-423b-9601-0b32e3ba8a01.png">

**Comment by anastely** [comment]
Same issue RN ~  0.66.2 + 0.64.2

![issue](https://user-images.githubusercontent.com/24620979/140615463-ae857b9f-05d6-45f3-a58d-3a47dff37cd4.png)

**Comment by anastely** [comment]
@mweststrate

**Comment by mweststrate** [comment]
Please do provide some additional information, like the logs (under exclamation mark icon). Are you using a debug build? Please compare your setup with our reference example https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample, make sure that Flipper is started as part of the debug build. Does the reference example work correctly?

**Comment by mweststrate** [comment]
> @mweststrate

Please don't ping individuals unless there is a specific reason to do so.

**Comment by realtril** [comment]
@mweststrate that's what I got:

in ```androidmanifest.xml```

<img width="567" alt="Screen Shot 2021-11-26 at 1 18 48 PM" src="https://user-images.githubusercontent.com/53015418/143573223-99ec5561-6dd2-41e6-b483-71394ecc836a.png">

```adb devices```
![Screen Shot 2021-11-26 at 1 21 31 PM](https://user-images.githubusercontent.com/53015418/143573525-a75e17c3-0679-402a-86c5-770120b07c45.png)

**Comment by mweststrate** [comment]
Sorry that is not enough information to be able to act upon. Can you check if the reference example does work correctly? That gives some clarity on where potential problems might be.

**Comment by rafirr** [comment]
@mweststrate i've similar issue, the funny thing is that it worked on friday. I've tried with a new Flipper SDK (0.123.0), but no success. I've connection to device, but no to app.

Flipper logs:
![image](https://user-images.githubusercontent.com/8736261/144849814-2dc6bccd-9acc-4fd1-a90d-bb47a7daaa56.png)

Diagnostics screen:
![Screenshot_2021-12-06-13-52-51-163_com primateapp](https://user-images.githubusercontent.com/8736261/144850063-98fe76f0-515d-43bc-9e76-394c558d96bb.jpg)

RN: 0.66.3
Flipper SKD: now 0.123.0, previously 0.99.0

**Comment by rafirr** [comment]
@mweststrate nevermind, after restart my computer, it's working :)

**Comment by realtril** [comment]
@mweststrate All debugging on Hermes, React DevTools, and logs for device & JS work just fine, including breakpoints. The only problem is I still see "NO APPLICATION SELECTED"

My AndroidManifest.xml in both debug and main contains 'android:name=".MainActivity" and the app itself works fine.

ADB devices lists the device correctly, and this project has been working fine for over 3 years with React Native Debugger so we know most if not all of the setup is correct (due to the expo upgrade, I needed to drop off from react-native debugger and switch to Flipper)

**Comment by sparlampe** [comment]
I had exactly the same simptoms. Then I discovered that in settings the path of the android SDK was incorrect. It was pointing to `/opt/something`.. I have changed it to `myHome/Android/Sdk` and everything worked. 
OS: Ubuntu
Flipper device: 0.126.0
Flipper desktop: 0.127.0

The mobile application fails to start with Flipper 0.127.0 with the error 
`SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found`
This is the reason for the version mismatch above.

**Comment by sabun123** [comment]
I'm experiencing the `NO APPLICATION SELECTED` issue with the latest Flipper and React Native at the time of this writing as well. This is for both iOS and Android, using the simulators/emulators.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/3523483/154984146-cca07f6b-3089-465e-bde0-b9be71a908db.png">


This poses a problem as I'm unable to use Flipper's plugins for:

- Redux
- Network

What does work even with this error:

- Logs for `Device` and `React Native`
- React DevTools

The version of Flipper we're using is `0.135.0`.
The version of React Native we're using is `0.67.2`.

I've gone as far back as Flipper version `0.127.0` and no dice. This issue persists.

I'd be happy getting this working just on iOS at least. Our `Podfile` has the following set for Flipper:
```JavaScript
# Enables Flipper.
use_flipper!({'Flipper' => '0.135.0'})
```

## Additional information:
OS: macOS Monterey version 12.2
System: Intel x86 (i5 quad core)
Yarn: 1.22.10
Xcode: 13.2.1
Simulators: iPhone X (iOS 12.4), iPhone 13 Pro Max (iOS 15)
Android Studio: 2020.2.1 Arctic Fox
Emulators: Pixel 2 (Android 10 and 11)

## Questions

1. Am I missing something during setup that's possibly not documented currently?
2. Is Flipper known to work with the latest React Native version for this feature or is it currently untested?

**Comment by lblasa** [comment]
Hi @sabun123, sorry to hear you're having issues. I've just tried with:
- react-native: 0.67.2
- react-native-flipper: 0.131.1
- Flipper: 0.135.0

The application appeared on the drop down and got connected, at least on iOS simulator. Can you please try the same on your end? I used the bundled ReactNativeExample app.

**Comment by sabun123** [comment]
Hey @lblasa thanks for getting back to me on this.

I've tried the ReactNativeFlipperExample app, and it does work with Flipper correctly.

The major difference between my project and the ReactNativeFlipperExample project appears to be a single dependency:

```JavaScript
"react-native-flipper": "^0.131.0"
```

I added it to the package.json file along with this section from the example app package.json:
```JavaScript
  "relativeDependencies": {
    "react-native-flipper": "../react-native-flipper"
  }
```

Adding this in seems to break the build though:
```JavaScript
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **
```

These differences don't seem to be in the documentation [https://fbflipper.com/docs/getting-started/react-native/](https://fbflipper.com/docs/getting-started/react-native/) and I can't find it on the Github page either. 

Am I on the right path here, and is there a way to overcome that build error? 
Or am I completely off the course here?

**Comment by lblasa** [comment]
I would:
- Remove the relativeDependencies. ReactNativeExample is contained within the react-native folder, so is referencing that. So unless your project is within the same directory, then it wouldn't work.
- Run `pod install --repo-update` in your project folder.

FlipperClient is defined in Flipper. So it looks like is completely missing.

**Comment by sabun123** [comment]
Thanks for pointing that out @lblasa , I did not fully understand what the relativeDependencies piece was doing. I have removed it from the package.json file upon your guidance.

Tried doing a `pod install --repo-update` however it didn't change the outcome.

### What else I've tried
Removed the `Pods` folder and the `Podfile.lock` file and tried from scratch:
```
Installing Flipper (0.135.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.1.7)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)
Installing Flipper-Glog (0.3.9)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.4.3)
Installing FlipperKit (0.135.0)
...
Installing react-native-flipper (0.131.1)
```
As far as can be seen, looks like cocoapods is installing the dependencies correctly.

**Outcome**: Still failing at the build stage

Went one step further:

1. Removed node_modules and re-did `yarn install`
2. Removed `Pods` and `Podfile.lock` and re-did `pod install --repo-update`
3. In Xcode, hit CMD+SHIFT+K to clean out the build folder
4. In the simulator, delete all previous app versions installed so it's barebones again

Ran the build once more

**Outcome**:  Still failing with
```JavaScript
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

No dice so far, any other ideas to try to get this working?

**Comment by stanwrkt** [comment]
Check your AppDelegate.m file, maybe you forgot to add the initialization code there.

**Comment by gax97** [comment]
I can add that this issue occurs to me on iOS only if I select some build scheme that is different from the "main" scheme.

**Comment by hoangnguyen8895** [comment]
Update Android sdk location in Flipper's settings and reload. Hope it helps :D

**Comment by gax97** [comment]
I can add that my issue was resolved after I specified flipper version an build configurations in Podfile likes this for example:
```
use_flipper!({ 'Flipper' => '0.137.0' }, configurations: ['Debug', 'Dev.Debug'])
```

**Comment by sabun123** [comment]
@gax97 you are an amazing individual!

This did the trick, would be lovely to have this in the official Flipper setup documentation for those of us in production setups where we support multiple build configurations.

I modified my Podfile to the following (the ... are skipped lines):
```
flipperkit_version = '0.135.0'

...

project 'myapp',
        'DEV.Debug' => :debug,
        'DEV.Release' => :release, 
        'SIT.Debug' => :debug,
        'SIT.Release' => :release, 
        'UAT.Debug' => :debug,
        'UAT.Release' => :release, 
        'CI.SIT.Debug' => :debug,
        'CI.SIT.Release' => :release,
        'CI.UAT.Debug' => :debug,
        'CI.UAT.Release' => :release,
        'PROD.Debug' => :debug,
        'PROD.Release' => :release
...

  use_flipper!({ 'Flipper' => flipperkit_version, 'Flipper-Folly' => '2.6.10', configurations: ['DEV.Debug', 'SIT.Debug', 'UAT.Debug', 'CI.SIT.Debug', 'CI.UAT.Debug'], 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4', 'OpenSSL-Universal' => '1.1.1100' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

  end
```

As can be seen we have a tonne of build configurations setup, and after defining it in `use_flipper` explicitly, the app gets picked up by Flipper immediately! No more "No Application Selected" issue.

Thanks again @gax97 for sharing your findings.

**Comment by vmechiev** [comment]
Hello! I have the same issue. I did everything that has been described above, but I am still not succeed...

**Comment by NomanGul** [comment]
+1 bump

**Comment by Vitor-Felix** [comment]
I tried everything above, but it still with the "NO APPLICATION SELECTED" status. It's pretty interesting because it was working just fine, then suddenly one day, it couldn't find any app in any device. I love the project and hope it start to work again some day.

**Comment by Vitor-Felix** [comment]
I tried everything above, but it still with the "NO APPLICATION SELECTED" status. It's pretty interesting because it was working just fine, then suddenly, it just couldn't find any app on any device. I love the project and hope it starts to work again someday.

**Comment by Vitor-Felix** [comment]
I tried everything above, but it still with the "NO APPLICATION SELECTED" status. It's pretty interesting because it was working just fine, then suddenly, it just couldn't find any app on any device. I love the project and hope it starts to work again someday, as easy as it was.

**Comment by mweststrate** [comment]
Hi folks, there is many different reasons why Flipper might  not be able to connect, and with +1 ing we don't know anything more about your situation, nor gives it any signal on what we could potentially  improve on our side. There is sadly quite a lot of reasons why things might  not connect, like adb crashes, xcode upgrades, mismatching RN and Flipper versions, not using a debug build, etc. Regularly even a reboot can fix issues.
If you need help with Flipper not connecting:

1. Clone the reference project https://github.com/facebook/flipper/tree/main/react-native/ReactNativeFlipperExample and see if that one corrects correctly
2. If not, verify doctor, and file an issue
3. If it connects, compare that projects setup with your own.
4. If all versions are up to date, and there is a meaningful difference causing a connecting issue, only then open an issue with a small repro and environment info. Before going through those steps, there is usually little meaningful signal we can act on.

For now closing this issue, since there are multiple separate discussions going on, but none from the OP

**Comment by karatekid430** [comment]
Oops, in a React Native upgrade I had clobbered the initialisation code in AppDelegate.m, check that you have not done the same. Fixed now.

**Comment by nebeus-dev** [comment]
RN 0.69.5. Application detecting works after adding this code to AppDelegate.mm https://fbflipper.com/docs/getting-started/react-native-ios/#react-native-067 . Flipper configuration in Podfile: `use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled(["DebugDevelopment","DebugStaging","DebugProduction"], { 'Flipper' => '0.162.0' }),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )`

**Comment by andreyboberskiy** [comment]
RN 0.69.5. Application detecting works after adding [this code](https://fbflipper.com/docs/getting-started/react-native-ios/#react-native-067) to AppDelegate.mm. Flipper configuration inside use_react_native: `:flipper_configuration => FlipperConfiguration.enabled(["DebugDevelopment","DebugStaging","DebugProduction"], { 'Flipper' => '0.162.0' }),`

**Comment by Dannark** [comment]
I got it!
For anyone in the future, I was able to run after fixing 3 erros: (My problem only occurs for iOS and Im using React Native 0.67 solution from the docs even though im on 0.68+)

1º problem was the `#if DEBUG` that wasnt working even using target `Development` in xCode for our projet, So I had to follow this [instructions ](https://stackoverflow.com/questions/58876224/condition-if-debug-else-if-production-not-working-in-swift) to add it

2º problem was the next line `#if FB_SONARKIT_ENABLED` also didn't work so I had to comment it [refer to](https://stackoverflow.com/questions/72150775/fb-sonarkit-enabled-1-flag-not-working-when-initialising-flipper-in-ios-app-ios)

3º problem was `No such module 'FlipperKit' found` then I realized I didn't even had the necessary libs in my project! 

The docs should be more clear about the FULL instalation process, there are a lot of parts missing here.

**Comment by DominicTobias** [comment]
For me I changed the flipper version to the same as the desktop standalone one in `Podfile` (`use_flipper`) and `gradle.properties` (`FLIPPER_VERSION`) and I also went to Flipper Settings > Android SDK location and changed that to the location of my Android SDK:

Bad:
![Screenshot 2022-10-03 at 10 00 57 AM](https://user-images.githubusercontent.com/760314/193540278-b772da31-8f25-432c-91b4-d7fc76b78666.png)

Good:
![Screenshot 2022-10-03 at 10 04 12 AM](https://user-images.githubusercontent.com/760314/193540325-bcd0abc0-9ed1-45b0-8873-a4700ddfbed4.png)

**Comment by Reactor-Labs** [comment]
These are the steps I took to fix the issue

Install and configure idb 

```
$ brew tap facebook/fb
$ brew install idb-companion
$  pip3 install fb-id
```

Set the idb binary location in flipper -> settings to `/opt/homebrew/bin/idb`

Update my podfile for RN 0.69.0

```
 use_flipper!({ 'Flipper' => '0.166.0' })
```
This should match your installed version of flipper in my case 0.166.0

**Comment by Dat-Mobile** [comment]
I was able to solve that on Android

open `ReactNativeFlipper.java` file

In the first line `package com.yourappname;` change it to exactly your package name inside `AndroidManifest.xml`

**Comment by badaz** [comment]
> I was able to solve that on Android
> 
> open `ReactNativeFlipper.java` file
> 
> In the first line `package com.yourappname;` change it to exactly your package name inside `AndroidManifest.xml`

This last comm' saved me ! I had replaced the whole file contents during a RN update, forgetting to update the package name at the top of the file, tx

**Comment by vikingprank** [comment]
Hello, I was having the "NO APPLICATION SELECTED" issue with flipper and managed to detect my app in flipper after several hours of searching. I'm using Flipper 0.183.0 and in my package.json, 0.183.0 as well. react-native: 0.69.7
1) I installed the reactnativeflipperexample project on my android phone, and flipper was able to pick it up. Figured the problem was in the config of my project.
2) I changed the FLIPPER_VERSION variable in android/gradle.properties to the same as the demo project: 0.171.1. This didn't change anything. Ran "cd android/ && ./gradlew" clean to take the changes.
3) Inside mobile/android/app/build.gradle, I had this line that was not in the demo project: "exclude group:'com.squareup.okhttp3', module:'okhttp'", So I removed it. Still no luck.
4) In MainApplication.java I had:
Class<?> aClass = Class.forName("com.facebook.flipper.ReactNativeFlipper");
But in demo they had:
Class<?> aClass = Class.forName("com.reactnativeflipperexample.ReactNativeFlipper");
So, I changed "facebook" to the name in the AndroidManifest of my project.
5) Build the project, it appeared in the Flipper interface for the first time.
Hope this helps!

**Comment by sesm** [comment]
I was having "NO APPLICATION SELECTED" issue on iOS with RN 0.71.3.
Turns out, the root cause was that I didn't update `AppDelegate.m` correctly when upgrading, in the end of `didFinishLaunchingWithOptions` I had `return YES;` instead of `return [super application:application didFinishLaunchingWithOptions:launchOptions];`

**Comment by Seunope** [comment]
The following worked for me.
1. Set the path to Android SDK correctly
2. Ensure the watchman is set up
3. Ensure the Setup Doctor is not flagging any issue

None of the above resolved the issue until  I uninstall the app from the device, close the Metro Bundler terminal, and then run `yarn android` after this Fipper "NO APPLICATION SELECTED" error disappeared. 

Desktop FLIPPER_VERSION=0.201.0
React native Android FLIPPER_VERSION=0.125.0

**Comment by manosKas** [comment]
@Seunope should i run yarn android (or ios) even though i use npm ?

**Comment by Seunope** [comment]
> @Seunope should i run yarn android (or ios) even though i use npm ?

You can use either yarn or npm, it should still work.

**Comment by simonsmith** [comment]
Just wanted to add what was needed to fix it for me. This is on `0.72.3`:

**AppDelegate.swift**
```diff
import UIKit
+import FlipperKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
+        let client = FlipperClient.shared()
+        let layoutDescriptorMapper = SKDescriptorMapper(defaults: ())
+        client?.add(FlipperKitLayoutPlugin(rootNode: application, with: layoutDescriptorMapper!))
+        client?.add(FKUserDefaultsPlugin(suiteName: nil))
+        client?.add(FlipperKitReactPlugin())
+        client?.add(FlipperKitNetworkPlugin(networkAdapter: SKIOSNetworkAdapter()))
+        client?.start()

        window = UIWindow()
        window?.rootViewController = TabViewController()
        window?.makeKeyAndVisible()
            
        return true
    }
}

```

**Comment by thoth-seshat** [comment]
Hum.. I'm having this problem as well. Expo with filler 0.210.0

**Comment by neethanz** [comment]
> For me I went to Flipper Settings > Android SDK location and changed that to the location of my Android SDK:
> 
> Bad: ![Screenshot 2022-10-03 at 10 00 57 AM](https://user-images.githubusercontent.com/760314/193540278-b772da31-8f25-432c-91b4-d7fc76b78666.png)
> 
> Good: ![Screenshot 2022-10-03 at 10 04 12 AM](https://user-images.githubusercontent.com/760314/193540325-bcd0abc0-9ed1-45b0-8873-a4700ddfbed4.png)



> For me I went to Flipper Settings > Android SDK location and changed that to the location of my Android SDK:
> 
> Bad: ![Screenshot 2022-10-03 at 10 00 57 AM](https://user-images.githubusercontent.com/760314/193540278-b772da31-8f25-432c-91b4-d7fc76b78666.png)
> 
> Good: ![Screenshot 2022-10-03 at 10 04 12 AM](https://user-images.githubusercontent.com/760314/193540325-bcd0abc0-9ed1-45b0-8873-a4700ddfbed4.png)

Thank you , Its worked for me - 18-08-23

**Comment by mguellsegarra** [comment]
> I was having "NO APPLICATION SELECTED" issue on iOS with RN 0.71.3. Turns out, the root cause was that I didn't update `AppDelegate.m` correctly when upgrading, in the end of `didFinishLaunchingWithOptions` I had `return YES;` instead of `return [super application:application didFinishLaunchingWithOptions:launchOptions];`

This fixed my error, using React Native 0.71.5 and Flipper 0.218.0

Thank you so much!

**Comment by dengcqw** [comment]
> Thanks for pointing that out @lblasa , I did not fully understand what the relativeDependencies piece was doing. I have removed it from the package.json file upon your guidance.
> 
> Tried doing a `pod install --repo-update` however it didn't change the outcome.
> 
> ### What else I've tried
> Removed the `Pods` folder and the `Podfile.lock` file and tried from scratch:
> 
> ```
> Installing Flipper (0.135.0)
> Installing Flipper-Boost-iOSX (1.76.0.1.11)
> Installing Flipper-DoubleConversion (3.1.7)
> Installing Flipper-Fmt (7.1.7)
> Installing Flipper-Folly (2.6.10)
> Installing Flipper-Glog (0.3.9)
> Installing Flipper-PeerTalk (0.0.4)
> Installing Flipper-RSocket (1.4.3)
> Installing FlipperKit (0.135.0)
> ...
> Installing react-native-flipper (0.131.1)
> ```
> 
> As far as can be seen, looks like cocoapods is installing the dependencies correctly.
> 
> **Outcome**: Still failing at the build stage
> 
> Went one step further:
> 
> 1. Removed node_modules and re-did `yarn install`
> 2. Removed `Pods` and `Podfile.lock` and re-did `pod install --repo-update`
> 3. In Xcode, hit CMD+SHIFT+K to clean out the build folder
> 4. In the simulator, delete all previous app versions installed so it's barebones again
> 
> Ran the build once more
> 
> **Outcome**: Still failing with
> 
> ```js
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_FlipperClient", referenced from:
>       objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> No dice so far, any other ideas to try to get this working?
read react-native-flipper.podspec, use "export PRODUCTION=1; pod install" for run for release build,  "unset  PRODUCTION; pod install"  for debug build.  this is bad develop experience.

**Comment by dengcqw** [comment]
> I'm experiencing the `NO APPLICATION SELECTED` issue with the latest Flipper and React Native at the time of this writing as well. This is for both iOS and Android, using the simulators/emulators.
> 
> <img alt="image" width="279" src="https://user-images.githubusercontent.com/3523483/154984146-cca07f6b-3089-465e-bde0-b9be71a908db.png">
> 
> This poses a problem as I'm unable to use Flipper's plugins for:
> 
> * Redux
> * Network
> 
> What does work even with this error:
> 
> * Logs for `Device` and `React Native`
> * React DevTools
> 
> The version of Flipper we're using is `0.135.0`. The version of React Native we're using is `0.67.2`.
> 
> I've gone as far back as Flipper version `0.127.0` and no dice. This issue persists.
> 
> I'd be happy getting this working just on iOS at least. Our `Podfile` has the following set for Flipper:
> 
> ```js
> # Enables Flipper.
> use_flipper!({'Flipper' => '0.135.0'})
> ```
> 
> ## Additional information:
> OS: macOS Monterey version 12.2 System: Intel x86 (i5 quad core) Yarn: 1.22.10 Xcode: 13.2.1 Simulators: iPhone X (iOS 12.4), iPhone 13 Pro Max (iOS 15) Android Studio: 2020.2.1 Arctic Fox Emulators: Pixel 2 (Android 10 and 11) iOS using Hermes: NO Android using Hermese: YES
> 
> ## Questions
> 1. Am I missing something during setup that's possibly not documented currently?
> 2. Is Flipper known to work with the latest React Native version for this feature or is it currently untested?

I fix it by create link to /usr/local/bin/idb-companion. because maybe brew link idb-companion to /opt/brew/...
flipper maybe use the fullpath /usr/local/bin/idb-companion

**Comment by pavelpashkovsky** [comment]
![image](https://github.com/facebook/flipper/assets/7372044/8bb8c4d7-b090-4d19-906a-be54aa399883)

**Comment by annewanghy** [comment]
my setting is right, and I'm trying to use latest version  of flipper 0.239.0, react-native 0.68.

set in Podfile
```
use_flipper!({ 'Flipper' => '0.239.0' }, configurations: ['Debug', 'Staging'])
```

I can see it's connect to my app, it can see logs, but it cannot use redux tool. trying many solutions and they all failed, is there anyone has the same problem and fixed it? 

<img width="613" alt="image" src="https://github.com/facebook/flipper/assets/18532655/de630b47-fb78-4247-8b41-a905cd27ffe7">
```
➜  ios git:(gh37-upgrade-react-native) ✗ whereis idb
idb: /usr/local/bin/idb
```

<img width="527" alt="image" src="https://github.com/facebook/flipper/assets/18532655/85a828a9-23b1-4f44-80fb-4435fb95e56a">


<img width="601" alt="image" src="https://github.com/facebook/flipper/assets/18532655/c8bb57dc-f80e-44bd-b143-168c0d596a84">

**Comment by annewanghy** [comment]
thank you @sabun123 you save my day https://github.com/facebook/flipper/issues/3027#issuecomment-1057057815

**Comment by mununki** [comment]
> I was having "NO APPLICATION SELECTED" issue on iOS with RN 0.71.3. Turns out, the root cause was that I didn't update `AppDelegate.m` correctly when upgrading, in the end of `didFinishLaunchingWithOptions` I had `return YES;` instead of `return [super application:application didFinishLaunchingWithOptions:launchOptions];`

It works for me. Thanks!

**Comment by jemmycalak** [comment]
makesure your project in debug mode.
