### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ColtonIdle** [facebook/flipper#3042]
Updated from ("com.facebook.soloader:soloader:0.10.1") to ("com.facebook.soloader:soloader:0.10.3")
and from ("com.facebook.flipper:flipper:0.105.0") to ("com.facebook.flipper:flipper:0.119.0") and am met with this error on launcher.

```
2021-10-26 15:19:13.311 8913-8956/com.rollertoaster.app.beta E/re.app.bet: ----- class 'Lcom/facebook/flipper/android/FlipperClientImpl;' cl=0x12ca1040 -----
      objectSize=320 (224 from super)
      access=0x0000.0000
      super='java.lang.Class<java.lang.Object>' (cl=0x0)
      interfaces (1):
         0: java.lang.Class<com.facebook.flipper.core.FlipperClient> (cl=0x12ca1040)
      vtable (12 entries, 11 in super):
         0: void com.facebook.flipper.android.FlipperClientImpl.addPlugin(com.facebook.flipper.core.FlipperPlugin)
         1: void com.facebook.flipper.android.FlipperClientImpl.addPluginNative(com.facebook.flipper.core.FlipperPlugin)
         2: com.facebook.flipper.core.FlipperPlugin com.facebook.flipper.android.FlipperClientImpl.getPlugin(java.lang.String)
         3: com.facebook.flipper.core.FlipperPlugin com.facebook.flipper.android.FlipperClientImpl.getPluginByClass(java.lang.Class)
         4: java.lang.String com.facebook.flipper.android.FlipperClientImpl.getState()
         5: com.facebook.flipper.core.StateSummary com.facebook.flipper.android.FlipperClientImpl.getStateSummary()
         6: void com.facebook.flipper.android.FlipperClientImpl.removePlugin(com.facebook.flipper.core.FlipperPlugin)
         7: void com.facebook.flipper.android.FlipperClientImpl.removePluginNative(com.facebook.flipper.core.FlipperPlugin)
         8: void com.facebook.flipper.android.FlipperClientImpl.start()
         9: void com.facebook.flipper.android.FlipperClientImpl.stop()
        10: void com.facebook.flipper.android.FlipperClientImpl.subscribeForUpdates(com.facebook.flipper.core.FlipperStateUpdateListener)
        11: void com.facebook.flipper.android.FlipperClientImpl.unsubscribe()
      direct methods (4 entries):
         0: void com.facebook.flipper.android.FlipperClientImpl.<clinit>()
         1: void com.facebook.flipper.android.FlipperClientImpl.<init>(com.facebook.jni.HybridData)
         2: com.facebook.flipper.android.FlipperClientImpl com.facebook.flipper.android.FlipperClientImpl.getInstance()
         3: void com.facebook.flipper.android.FlipperClientImpl.init(com.facebook.flipper.android.EventBase, com.facebook.flipper.android.EventBase, int, int, int, int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
      instance fields (2 entries):
         0: java.util.Map com.facebook.flipper.android.FlipperClientImpl.mClassIdentifierMap
         1: com.facebook.jni.HybridData com.facebook.flipper.android.FlipperClientImpl.mHybridData
2021-10-26 15:19:13.312 8913-8956/com.rollertoaster.app.beta E/re.app.bet: Failed to register native method com.facebook.flipper.android.FlipperClientImpl.init(Lcom/facebook/flipper/android/EventBase;Lcom/facebook/flipper/android/EventBase;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V in /data/data/com.rollertoaster.app.beta/code_cache/.overlay/base.apk/classes19.dex
2021-10-26 15:19:13.313 8913-8956/com.rollertoaster.app.beta E/log: error java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/flipper/android/FlipperClientImpl;.init(Lcom/facebook/flipper/android/EventBase;Lcom/facebook/flipper/android/EventBase;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V"
2021-10-26 15:19:13.313 8913-8956/com.rollertoaster.app.beta A/re.app.bet: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/flipper/android/FlipperClientImpl;.init(Lcom/facebook/flipper/android/EventBase;Lcom/facebook/flipper/android/EventBase;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V"
    java_vm_ext.cc:579] (Throwable with no stack trace)
    java_vm_ext.cc:579] 
    java_vm_ext.cc:579]     in call to NewGlobalRef
    java_vm_ext.cc:579]     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class)
2021-10-26 15:19:13.404 8913-8956/com.rollertoaster.app.beta A/re.app.bet: runtime.cc:669] Runtime aborting...
    runtime.cc:669] Dumping all threads without mutator lock held
    runtime.cc:669] All threads:
    runtime.cc:669] DALVIK THREADS (34):
   runtime.cc:669] "FlipperConnectionThread" prio=4 tid=26 Runnable
    runtime.cc:669]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x13403408 self=0xb40000752c2f12e0
    runtime.cc:669]   | sysTid=8956 nice=10 cgrp=top-app sched=0/0 handle=0x73392ddcb0
    runtime.cc:669]   | state=R schedstat=( 43548797 45237038 63 ) utm=4 stm=0 core=0 HZ=100
    runtime.cc:669]   | stack=0x73391da000-0x73391dc000 stackSize=1039KB
    runtime.cc:669]   | held mutexes= "abort lock" "mutator lock"(shared held)
    runtime.cc:669]   native: #00 pc 000000000055f938  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
    runtime.cc:669]   native: #01 pc 0000000000676358  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+360)
    runtime.cc:669]   native: #02 pc 0000000000694034  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+920)
    runtime.cc:669]   native: #03 pc 000000000068db58  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+520)
    runtime.cc:669]   native: #04 pc 000000000068cd6c  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1464)
    runtime.cc:669]   native: #05 pc 0000000000626e50  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2164)
    runtime.cc:669]   native: #06 pc 000000000001595c  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
    runtime.cc:669]   native: #07 pc 0000000000014f8c  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+364)
    runtime.cc:669]   native: #08 pc 00000000004501fc  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2516)
    runtime.cc:669]   native: #09 pc 0000000000450274  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+108)
    runtime.cc:669]   native: #10 pc 00000000004424bc  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+140)
    runtime.cc:669]   native: #11 pc 0000000000440cc0  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+3180)
    runtime.cc:669]   native: #12 pc 000000000043f870  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+644)
    runtime.cc:669]   native: #13 pc 0000000000442920  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::NewRef(char const*, _JNIEnv*, _jobject*, art::IndirectRefKind)+648)
    runtime.cc:669]   native: #14 pc 0000000000680180  /apex/com.android.art/lib64/libart.so (art::Thread::SetClassLoaderOverride(_jobject*)+64)
    runtime.cc:669]   native: #15 pc 0000000000454028  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+3160)
    runtime.cc:669]   native: #16 pc 00000000000050dc  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+416)
    runtime.cc:669]   at java.lang.Runtime.nativeLoad(Native method)
    runtime.cc:669]   at java.lang.Runtime.nativeLoad(Runtime.java:1121)
    runtime.cc:669]   at java.lang.Runtime.load0(Runtime.java:927)
    runtime.cc:669]   - locked <0x010ae406> (a java.lang.Runtime)
2021-10-26 15:19:13.405 8913-8956/com.rollertoaster.app.beta A/er.app.bet: runtime.cc:669]   at java.lang.System.load(System.java:1620)
    runtime.cc:669]   at com.facebook.soloader.SoLoader$1.load(SoLoader.java:529)
    runtime.cc:669]   at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:77)
    runtime.cc:669]   at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1038)
    runtime.cc:669]   at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
    runtime.cc:669]   - locked <0x05c11ac7> (a java.lang.Object)
    runtime.cc:669]   at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
    runtime.cc:669]   at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
    runtime.cc:669]   at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
    runtime.cc:669]   at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
    runtime.cc:669]   at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
    runtime.cc:669]   - locked <0x064b38f4> (a com.facebook.flipper.android.FlipperThread)
```

**Comment by bizzguy** [comment]
I don't think the Flipper team has approved moving to soloader 0.10.3 yet.

**Comment by hbmartin** [comment]
Looks like this duplicates https://github.com/facebook/flipper/issues/2948

**Comment by blizzard7891** [comment]
@ColtonIdle  This issue is fixed??

**Comment by ColtonIdle** [comment]
Still broken for me. Haven't been able to use flipper in months. lol

**Comment by lblasa** [comment]
Hi, sorry for the lack of attention to this issue. I will be looking at it very shortly.

**Comment by blizzard7891** [comment]
@ColtonIdle I fixed this. just delete below ndk configuration in gradle.
            ndk {
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }

**Comment by ColtonIdle** [comment]
I don't have proguard on debug builds.
