### ISSUE TITLE
 Failed to find device error on Flipper 0.133.1

### ISSUE THREAD

**Issue by kbirgoren** [facebook/flipper#3432]
## 🐛 Bug Report
As soon as I open the Flipper, I get `Connection failed` error.

Failed to find device '7F017CFA-5EAB-4285-8AED-77E14A717BCE' while trying to connect app 'MyApp'

Everything works fine on the Android emulator but not in the iOS simulator

## To Reproduce
- Start the iOS simulator
- Open the Flipper App

## Environment
- macOS Monterey 12.0.1
- Simulator: iPhone 13 - iOS 15.0
- Flipper Version: 0.133.1
- React Native: 0.67.2

## Flipper logs
**Failed to find device '7F017CFA-5EAB-4285-8AED-77E14A717BCE' while connection app 'MyApp' Error: Timed out waiting for device 7F017CFA-5EAB-4285-8AED-77E14A717BCE for client MyApp
    at file:///Applications/[Flipper.app/Contents/Resources/app.asar/bundle.js:4209:5711](http://flipper.app/Contents/Resources/app.asar/bundle.js:4209:5711)**

**Comment by aigoncharov** [comment]
@kbirgoren could you attach complete Flipper logs (like in [this post](https://github.com/facebook/flipper/issues/3430#issuecomment-1035531806))?

**Comment by kbirgoren** [comment]
> @kbirgoren could you attach complete Flipper logs (like in [this post](https://github.com/facebook/flipper/issues/3430#issuecomment-1035531806))?

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/26083998/153613492-08ed1ea0-c2c9-46e6-96a1-cb4461d5f5bd.png">

@aigoncharov here you can find the screenshot of the logs.

**Comment by essana3** [comment]
Same here

**Comment by aigoncharov** [comment]
@kbirgoren @essana3 would you happen to be on M1 Macs by any chance?

**Comment by essana3** [comment]
> @kbirgoren @essana3 would you happen to be on M1 Macs by any chance?

Yes

**Comment by aigoncharov** [comment]
#3392 should hopefully fix it once it lands then.

**Comment by aigoncharov** [comment]
1. What is your Flipper client version (https://fbflipper.com/docs/getting-started/react-native-ios/#react-native-063)?
2. Do you see the same error running our Sample app -https://github.com/facebook/flipper#react-native-sdk--sample-app ?

**Comment by kbirgoren** [comment]
> 1. What is your Flipper client version (https://fbflipper.com/docs/getting-started/react-native-ios/#react-native-063)?
> 2. Do you see the same error running our Sample app -https://github.com/facebook/flipper#react-native-sdk--sample-app ?

Hey Andrey,

- There is no Flipper version specified in my pod file. I use `use_flipper!()`
- Unfortunately, I still have the same issue even with the Sample app. You can see the screenshot of the logs below.

It was actually working fine before I upgrade it to the latest version. I tried to revert to the previous version that I use which was `0.129.0` but that did not solve the issue either.

So now, I can still get the console logs from the project but I can't watch the network calls.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/26083998/153716274-602d1c23-85e2-4529-a2c6-28fc2e76e2b2.png">

**Comment by nlindroos** [comment]
Fixed a similar issue by upgrading _idb-companion_ from 1.0.14 -> 1.1.6.

This can be done by running 
```sh
brew update && brew upgrade idb-companion
```

<hr>

Found the underlying issue from the console in Flipper, (`option` + `command` + `i` to open console), where the command `~/Library/Python/3.8/bin/idb list-targets --json` resulted in an error.

After upgrading _idb-companion_, the `list-targets` command succeeds.

<hr>
@kbirgoren You should specify an exact version of Flipper in your Podfile, e.g. use_flipper!({ 'Flipper'=> '0.135.0' }) if you're using the most current recent version right now.

**Comment by kbirgoren** [comment]
@nlindroos Thanks for your message.

I just installed client version 0.99.0 and now everything seems to be working.

Specifying a version in Podfile did not help me either. I also experienced the same issue with Flipper's sample app.

**Comment by gmonte** [comment]
This works for me:
 ```shell
 brew update && brew upgrade idb-companion
 ```


> Fixed a similar issue by upgrading _idb-companion_ from 1.0.14 -> 1.1.6.
> 
> This can be done by running
> 
> ```shell
> brew update && brew upgrade idb-companion
> ```
> 
> Found the underlying issue from the console in Flipper, (`option` + `command` + `i` to open console), where the command `~/Library/Python/3.8/bin/idb list-targets --json` resulted in an error.
> 
> After upgrading _idb-companion_, the `list-targets` command succeeds.
> 
> @kbirgoren You should specify an exact version of Flipper in your Podfile, e.g. use_flipper!({ 'Flipper'=> '0.135.0' }) if you're using the most current recent version right now.

**Comment by essana3** [comment]
This issue has been fixed in idb-companion 1.1.7.
Make sure to uninstall the old version and install the new one since it supports m1 now.

**Comment by kbirgoren** [comment]
I am still facing with the same issue even on Flipper 0.144.0, I can only run it without any issues with Flipper 0.99.0

**Comment by jqn** [comment]
Following this doc should be able to help anyone trying to get Flipper working correctly https://fbflipper.com/docs/getting-started/react-native/

**Comment by Mainstreamlos** [comment]
I just restarted my smartphone, run the Flipper App again and it works.

**Comment by redbluenat** [comment]
For this worked M2: 

```
brew tap facebook/fb
brew install idb-companion
```

**Comment by akshayeshenoi** [comment]
Turns out _both_ `idb` and `idb-companion` are required. 

From [facebook/idb](https://github.com/facebook/idb):

> `idb` is made up of 2 major components, each of which needs to be installed separately.
> 
> ### `idb` companion
> 
> Each target (simulator/device) will have a companion process attached allowing `idb` to communicate remotely.
> 
> The `idb` companion can be installed via brew or built from [source](https://github.com/facebook/idb)
> 
> ```
> brew tap facebook/fb
> brew install idb-companion
> ```
> Note: Instructions on how to install brew can be found [here](https://brew.sh)
> 
> ### `idb` client
> 
> A cli tool and python client is provided to interact with `idb`.
> 
> It can be installed via pip:
> 
> ```
> pip3.6 install fb-idb
> ```
> Note: The idb client requires python 3.6 or greater to be installed.

**Comment by Cozy490** [comment]
<img width="1099" alt="image" src="https://github.com/facebook/flipper/assets/39758978/9815c113-11f3-48b6-8bf1-14c1fc3b82e6">
<img width="942" alt="image" src="https://github.com/facebook/flipper/assets/39758978/b4f7121b-834a-4498-b103-af7254c89834">
因为这里读不到ios的设备，各位有具体解决办法吗
