### ISSUE TITLE
Flipper Doctor complains Android SDK is not installed

### ISSUE THREAD

**Issue by paour** [facebook/flipper#667]
## 🐛 Bug Report

I've been using Flipper since before the name change and it's always worked fine (still does).

However, on each launch, I get an error banner claiming there are problems with my install.

![Flipper](https://user-images.githubusercontent.com/90963/69944000-7c613380-14e6-11ea-8c18-258d34c9127a.png)

My Android SDK is configured correctly, and complete.

![Flipper](https://user-images.githubusercontent.com/90963/69944028-9733a800-14e6-11ea-8df1-65e2cbcc564d.png)

![android-sdk](https://user-images.githubusercontent.com/90963/69944033-9c90f280-14e6-11ea-96c5-0602dd969e46.png)

## To Reproduce

Launch Flipper, or start Doctor.

## Expected Behavior

Doctor should not claim there is an error with my setup. Of if there really are, it should describe the issue in a way that makes it actionable.

## Environment

* MacOS High Sierra 10.13.6
* Flipper 0.29.4
```
adb --version
Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as /Applications/Dev/android-sdk/platform-tools/adb
```

**Comment by jknoxville** [comment]
Interesting, thanks for reporting.

What do you get if you run this from the command line?
`npx envinfo`

and also this:
`ANDROID_HOME=/Applications/Dev/android-sdk npx envinfo`

**Comment by paour** [comment]
Thank you for pointing me in the right direction! As you surmised, the tool didn't detect my Android SDK in with either command.

After looking at the source for `envinfo`,  I realized the root cause was [this issue](https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a).

The short-term fix for me is downgrading the version of Java I use by default, until Google finally updates their build tools for a current version of Java.

**Comment by ZacSweers** [comment]
I have this issue as well despite correct env info and my JAVA_HOME set to jdk 8

Env info is envinfo

```
Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 25.0.2, 28.0.3, 29.0.0, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: 21.0.5935234
```

It would be tremendously helpful if the doctor displayed some explanation as to _why_ it believes it's failed. The current screen gives no actionable information to the developer.

![image](https://user-images.githubusercontent.com/1361086/72037948-c79cfd80-326d-11ea-968e-f47c69d00ee1.png)

**Comment by nikoant** [comment]
@ZacSweers are you using Flipper v0.30.1?

**Comment by zlil** [comment]
@nikoant  I am using Flipper v0.30.1? and also having the same issue

**Comment by nikoant** [comment]
@zlil, right, I think the issue was fixed after v0.30.1 released. Could you try build Flipper from master and check?

**Comment by ericksli** [comment]
Same issue when using v0.30.1 on Windows 10. I have customized the Android SDK location in Flipper but it still shows the warning banner.

```
PS C:\Users\Eric> adb --version
Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as E:\Android\Sdk\platform-tools\adb.exe
```

```
PS C:\Users\Eric> npx envinfo
npx: installed 1 in 1.131s

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 24.26 GB / 31.92 GB
  Binaries:
    Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.21.0.
  IDEs:
    VSCode: 1.41.1 - C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Java: 12.0.1
  Databases:
    SQLite: 3.28.0 - E:\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
```

**Comment by ZacSweers** [comment]
This remains broken in 0.30.2

**Comment by nikoant** [comment]
@ZacSweers still reproducible with Java 8? That’s strange because the problem was that SDK is detected using sdkmanager, but the latter is not compatible with Java 9+. For Java 9 and 10 we implemented is a workaround, but not for 11+. This issue is planned to be fixed in Android Studio 3.6 release: https://issuetracker.google.com/issues/67495440.

As the issues with SDK detection are very environment-specific, could you please provide more information?
1. Post the full output of "npx envinfo"
2. Check that Android SDK path is correct in Flipper settings
3. Check whether you have environment variable ANDROID_HOME set on your machine? Does it points to the same dir as the SDK path in Flipper settings or different?

**Comment by ZacSweers** [comment]
I posted my info in my comment higher up, yes confirmed #2 and #3. It would be helpful if the app showed me some sort of diagnostic of what it tried to find and thinks is missing.

**Comment by nikoant** [comment]
@ZacSweers I've changed implementation of Android SDK detection to avoid using sdkmanager, and also added some (rather minimal) feedback for failed checks in this commit: https://github.com/facebook/flipper/commit/b625efee3d2fdce19c288c5135e12fe78e2572ca. Would be great if you can build from master and test this.

**Comment by ZacSweers** [comment]
Will give it a shot 👍

**Comment by ZacSweers** [comment]
Unfortunately I'm unable to build from master locally. Running on mac and running `yarn` completes successfully, but neither `yarn start` nor `yarn build` run successfully

```
zsweers@NYC-M-ZSWEERS01  ~/dev/misc/clones/flipper   master ●  yarn start
yarn run v1.21.1
$ cross-env NODE_ENV=development node scripts/start-dev-server.js
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'electron'
Require stack:
- /Users/zsweers/dev/misc/clones/flipper/scripts/start-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/zsweers/dev/misc/clones/flipper/scripts/start-dev-server.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zsweers/dev/misc/clones/flipper/scripts/start-dev-server.js'
  ]
}
```

```
yarn build --mac --version 0.1.0-local
yarn run v1.21.1
$ yarn rm-dist && cross-env NODE_ENV=production node scripts/build-release.js $@ --mac --version 0.1.0-local
$ rimraf dist
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'electron'
Require stack:
- /Users/zsweers/dev/misc/clones/flipper/src/utils/icons.js
- /Users/zsweers/dev/misc/clones/flipper/scripts/build-release.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/zsweers/dev/misc/clones/flipper/src/utils/icons.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zsweers/dev/misc/clones/flipper/src/utils/icons.js',
    '/Users/zsweers/dev/misc/clones/flipper/scripts/build-release.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ZacSweers** [comment]
Actually I see now that my yarn version is old, despite being the latest available on homebrew 🤔 . Will try installing manually

**Comment by ZacSweers** [comment]
Ok I'm not sure I understand. The README says it requires yarn 1.5+, yet that doesn't exist according to yarn's website

![image](https://user-images.githubusercontent.com/1361086/73128127-c28fbc00-3f98-11ea-92d7-446cf81a2d7e.png)

**Comment by nikoant** [comment]
@ZacSweers 1.21 is newer than 1.5 (1.05). I don't think the problem here is in yarn, it rather looks like "electron" module was not installed properly. Could you check that it exists in node_modules?

**Comment by ZacSweers** [comment]
Just tried a fresh clone in better wifi and looks like everything works! No more reported errors and I was successfully able to use flipper with my android app 🎉

**Comment by nikoant** [comment]
@ZacSweers good news! Thank you for checking this. 

I'm closing this issue then, SDK detection should work now disregard version of Java version.

**Comment by a-eid** [comment]
@nikoant I'm facing the same issue, 
flipper is weirdly saying that `android_home` is `/opt/android_sdk` and doesn't exit ..
which it is not true at all 
<img width="679" alt="Screen Shot 2020-04-08 at 00 06 51" src="https://user-images.githubusercontent.com/19273413/78724039-dbb7d000-792c-11ea-9026-6b45215ff547.png">

**Comment by paour** [comment]
@a-eid on Mac, console apps and gui apps do not necessarily share the same environment. Try exporting your console env:

```
launchctl setenv JAVA_HOME $JAVA_HOME
```

**Comment by joaovpmamede** [comment]
@paour same thing happening to me but that didn't fix it.
Anything else I should try?

**Comment by Victor502** [comment]
I fixed the error by going to my `local.properties` file in VS Code coping the `sdk.dir` which mine is `/Users/[MYUSER]/Library/Android/sdk` then I went in Filpper -> File -> Preferences and changed the Android SDK Location See image..
![Flipper](https://user-images.githubusercontent.com/22140740/79473985-dd8c2e00-7fd3-11ea-9a87-e8e13b8e41d1.png)
 
Then I clicked the `Apply and Restart` Button

**Comment by joaovpmamede** [comment]
Thanks @Victor502.
Ended up doing the same yesterday and it fixed the issue.

**Comment by cvharris** [comment]
I'm not sure why but I can't even edit the path in Flipper settings. It opens the dialog to pick the correct folder and after I do it just closes with no changes

**Comment by suarezluis** [comment]
in your terminal type ```echo $ANDROID_HOME``` that will give you the path to the Android SDK. 

Copy that path and paste it in Flipper -> Flie -> Preferences -> Android SDK Location.

![image](https://user-images.githubusercontent.com/20325995/82699020-7d6f5400-9c31-11ea-8132-9145b3fb5ceb.png)

Apply and restart and you should be done.

**Comment by alecpo** [comment]
You can also check on SDK manager at Android Studio the place of SDK :)

**Comment by kiranjd** [comment]
In your terminal, run `echo $ANDROID_HOME`, copy the path over to Flipper settings

**Comment by Cordobo** [comment]
On Mac OS I put `~/Library/Android/sdk` into flippers settings first, turns out, flipper wants an absolute path like `/Users/<username>/Library/Android/sdk`

**Comment by quyentran-agilityio** [comment]
> I fixed the error by going to my `local.properties` file in VS Code coping the `sdk.dir` which mine is `/Users/[MYUSER]/Library/Android/sdk` then I went in Filpper -> File -> Preferences and changed the Android SDK Location See image..
> ![Flipper](https://user-images.githubusercontent.com/22140740/79473985-dd8c2e00-7fd3-11ea-9a87-e8e13b8e41d1.png)
> 
> Then I clicked the `Apply and Restart` Button

This solution works for me. Thanks

**Comment by chr4ss12** [comment]
Flipper wants absolute path, maybe option to the GUI so the urls won't contain tilde?

**Comment by imsudesh** [comment]
<img width="1389" alt="Screenshot 2022-03-30 at 3 26 40 PM" src="https://user-images.githubusercontent.com/95416820/160805361-c22061d6-7ab4-4213-983a-8e4981e04ee8.png">

@suarezluis @Victor502 @quyentran-agilityio In my case this error shows and I am unable to update the sdk location. I am using mac.
`Failed to persist Flipper settings Error: EACCES: permission denied, mkdir '/Users/<username>/.config/flipper'`

**Comment by Victor502** [comment]
@imsudesh seems like a folder permission, [this](https://stackoverflow.com/questions/33896763/workspace-settings-permission-denied) could get you going in the right direction

**Comment by sanjeevkse** [comment]
> in your terminal type `echo $ANDROID_HOME` that will give you the path to the Android SDK.
> 
> Copy that path and paste it in Flipper -> File -> Preferences -> Android SDK Location.
> 
> ![image](https://user-images.githubusercontent.com/20325995/82699020-7d6f5400-9c31-11ea-8132-9145b3fb5ceb.png)
> 
> Apply and restart and you should be done.

For new Flipper (Mac version). Its under cog icon > settings
