### ISSUE TITLE
Problem building a plugin against latest flipper version: can't find 7zip package

### ISSUE THREAD

**Issue by jschear** [facebook/flipper#793]
## 🐛 Bug Report
I’m trying to update a flipper desktop plugin that I haven’t touched in a while, and when I add `"flipper": "latest"` as a dependency (or `yarn add flipper@latest`) and run `yarn` in my plugin directory, I get this error: 

```
yarn install v1.22.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning flipper > @types/redux-devtools-extension@2.13.2: This is a stub types definition for redux-devtools-extension (https://github.com/zalmoxisus/redux-devtools-extension). redux-devtools-extension provides its own type definitions, so you don't need @types/redux-devtools-extension installed!
warning flipper > npm-api > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning flipper > pkg > pkg-fetch > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning flipper > rsocket-tcp-server > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
error Couldn't find package "7zip@0.0.6" required by "electron-devtools-installer@^2.2.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "7zip-bin-mac@^1.0.1" required by "flipper@latest" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
It seems like I’m unable to fetch that specific dependency. I'm wondering if flipper is depending on a broken version. I can reproduce the issue with a fresh `package.json` with no other dependencies:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "flipper": "latest"
  }
}
```

If I steal the `yarn.lock` block for that dependency from flipper’s `yarn.lock` file (https://github.com/facebook/flipper/blob/master/yarn.lock#L5) I can build successfully (but that doesn't seem like a good idea).

## To Reproduce
1. Create a new package with `yarn init`
2. Add `"flipper": "latest"` as a dependency.
3. Attempt to download dependencies with `yarn install`

## Environment
Flipper desktop version: 0.31.1
MacOS: 10.14.6
Yarn: 1.22 (installed via Homebrew)

I'm no yarn expert... perhaps I'm missing some local configuration to fetch from the right registry?

**Comment by passy** [comment]
@jschear There were some issues with yarn and/or npm over the past few days. This has been fixed and shouldn't have anything to do with Flipper. Can you please retry?

**Comment by jschear** [comment]
Ah, gotcha, just found https://github.com/yarnpkg/yarn/issues/7902. It looks like that's what I'm hitting. I'm still seeing the error, but it doesn't seem related to Flipper. Thanks for your time!
