### ISSUE TITLE
iOS - react-native-flipper includes FlipperKit, even in Release configuration

### ISSUE THREAD

**Issue by TimBroddin** [facebook/flipper#976]
## 🐛 Bug Report
If you're using react-native-flipper and do `pod install`, the included files assume you have FlipperKit installed.

However, if you have lines like these in your Podfile, FlipperKit will only be installed when your application is run in Debug configuration.

```
def add_flipper_pods!
  version = '~> 0.33.1'
  pod 'FlipperKit', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
end

```

Creating a release build will fail.

I upgraded from RN 0.61.5 to 0.62 and did the migration by hand, so I might've missed something that prevents this bug from happening on a fresh 0.62 install.  

## To Reproduce
1. Install react-native
2. `npm i --save-dev react-native-flipper`
3. Do `pod install`
4. Create a release build
5. Get this error: 
```

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
```

When `react-native-flipper` is removed and `pod install` is ran again, a release build will compile again.

## Environment
iOS

**Comment by cekkaewnumchai** [comment]
cc. @priteshrnandgaonkar, @mweststrate

**Comment by Yallan** [comment]
Same here

**Comment by tr3v3r** [comment]
The same here

**Comment by MikhailVolkov350504** [comment]
Facing the same issue

**Comment by mweststrate** [comment]
Apologies for not updating the issue! @priteshrnandgaonkar landed a fix yesterday: https://github.com/facebook/react-native/commit/e5497ca8f6e3b240948fdbeef0ac2a710f25bb56, so this should be fixed in the next release, but if you don't want to await that, I think it should be possible to manually copy these changes.

**Comment by Yallan** [comment]
Fixed for me by remove react-native-flipper (installed when i add flipper-plugin-rn-redux-inspector)

**Comment by tr3v3r** [comment]
@mweststrate After upgrade to `react-native v. 0.62.2` and `react-native-flipper v. 0.37` the issue still presents ;(

**Comment by TimBroddin** [comment]
I can confirm that the workaround by @tr3v3r works!

**Comment by SaveYourTime** [comment]
For anyone who is facing the same issue with the react native version v0.62.0 or v0.62.1.
Check this out!

Following the upgrade helper to upgrade your project to react native v0.62.2
Checking your dependencies
If you don’t have react-native-flipper and flipper-plugin-rn-redux-inspector in your dependencies, the issue must be fixed after upgraded.
If you have either react-native-flipper or flipper-plugin-rn-redux-inspector just remove both of them.
npm uninstall react-native-flipper flipper-plugin-rn-redux-inspector
Remove node_modules and Pods
Run npm install (or yarn, if you use yarn) and cd ios && pod install

**Comment by priteshrnandgaonkar** [comment]
Closing this issue, feel free to reopen if the issue persists in `v0.62.2` with the above mentioned changes.

**Comment by AppSphere** [comment]
This is not fixed yet. Flipper is till included in release mode.

**Comment by mweststrate** [comment]
This issue is closed, please open a new issue including your build
configuration in the podspec file

**Comment by nvdnvd00** [comment]
After upgrade to react-native v. 0.63.0-rc.0 and react-native-flipper v. 0.39 the issue still presents 
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)
ld: symbol(s) not found for architecture arm64
```
Podfile
```

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'myApp' do
  platform :ios, '11.0'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'RSKImageCropper','~> 2.0.0'
  pod 'QBImagePickerController' ,'~> 3.4.0'
  pod 'Stripe', '~> 14.0.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Fabric', '~> 1.10.2'

    # React Native Maps dependencies
    rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'


    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])


  target 'myAppTests' do
    inherit! :complete
    # Pods for testing
  end

   # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'myApp-tvOS' do
  # Pods for myApp-tvOS

  target 'myApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```
Environment
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 68.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0-rc.0 => 0.63.0-rc.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by tr3v3r** [comment]
@nvdnvd00 have you tried 
https://github.com/facebook/flipper/issues/976#issuecomment-612874193

?

**Comment by nvdnvd00** [comment]
yeah, it's working
but i think we need a solution, not workaround

**Comment by aelesia** [comment]
Downgraded from 0.62.2 to 0.61.5 and my build times have decreased 250%. 

10 minutes locally down to 4 minutes.

30 minutes on Bitrise down to 12.5 minutes.

**Comment by mweststrate** [comment]
@alloy any idea how this can happen? will auto linking the react-native-flipper package cause the Flipper SDK to be included, even though that should be included in DEV builds only? Can we somehow mark react-native-flipper itself as dev only?

**Comment by alloy** [comment]
auto-link will indeed always activate pods it finds among react-native packages, regardless of configuration. However, it will also _skip_ auto-linking of any pod that was [explicitly activated by the user](https://github.com/react-native-community/cli/blob/48136adfb814d335e957e22129d049c4a05c8759/packages/platform-ios/native_modules.rb#L65-L68) in their `Podfile` **before** the `use_native_modules!` call; so I think the following should work:

```ruby
pod 'react-native-flipper', :path => '../node_modules/react-native-flipper', :configuration => 'Debug'
use_native_modules!
# ...
```

Can somebody please try and verify?

----

As for build times, such as those reported by @aelesia, there’s not much to be done there other than caching build artefacts, as there’s no way to tell Xcode to only build dependencies in specific configurations–we can only influence what will get linked.

**Comment by mweststrate** [comment]
@alloy is linking also skipped if the requires are always conditional and the module is never used in prod builds? (e.g. all calls are wrapped like `if (__DEV__) require('react-native-flipper').addPlugin({}) `)

**Comment by alloy** [comment]
Alas not, linking of native libraries does not depend on any runtime JS code.

**Comment by carolinafbarros** [comment]
Any update?

**Comment by mweststrate** [comment]
@carolinafbarros as far as I can see now, we should add https://github.com/facebook/flipper/issues/976#issuecomment-632697702 to the installation instructions as it looks like auto linking does not support linking libraries only in dev builds.

pinging @rickhanlonii to verify that assumption

**Comment by alloy** [comment]
@carolinafbarros It would be great if you could verify that my assumption actually works 🙏

**Comment by carolinafbarros** [comment]
@mweststrate @alloy 
Thanks, it's works 👍

**Comment by mweststrate** [comment]
Thanks for confirming @carolinafbarros!

This all makes me wonder, shouldn't this be an issue on Android as well?

**Comment by alloy** [comment]
Thanks for confirming @carolinafbarros! 🙌 

@mweststrate Probably good to double-check, but it would probably be best to do so in a new issue and close this one.

**Comment by mweststrate** [comment]
I just published `react-native-flipper@0.44.0-fix-976`, I'd be really grateful if someone could confirm that this fixes the issue!

The essence of the change is that the entire bindings are put in a `#ifdef DEBUG` macro, so that on release builds the implementation becomes empty and no dependencies from FlipperKit are loaded

**Comment by martinezguillaume** [comment]
Hello there, I think in your release (`0.44.0-fix-976`), there is an error inside `FlipperModule.m`
Line 29: 
```
 -(instancetype)init {
  }
```
we should remove this (Use of undeclared identifier 'instancetype' during build)

But if I'm building in release mode, I still have Flipper deps building... Should I remove these lines from my Podfile ? :
```
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
```

**Comment by alloy** [comment]
@mweststrate Why was there still a need for a fix like that? Is it not preferable to still allow the user to make that final decision? Perhaps this ultimately proves academic when it comes to Flipper, but at some point if somebody would need Flipper in a release build this makes that much harder.

**Comment by alloy** [comment]
@martinezguillaume See my earlier comment for a bit more details, but note that it only builds those deps, they are not included (by default).

**Comment by mweststrate** [comment]
@martinezguillaume thanks for testing! Apologies, I accidentally pushed an older version. `0.44.0-fix-976-2` shouldn't have the additional `init` mod.

**Comment by mweststrate** [comment]
@alloy so far the scope of Flipper has always been: not in release builds. Simply for the security risks (and perf impacts) it causes, so far I haven't got the impression that has caused any significant issues. So I think this solution is fine for now and everything being correct ootb is great I think.

**Comment by alloy** [comment]
I agree that having things work as expected by default is the way to go, I’m just generally interested to see if that can be provided without making it too hard to deviate. E.g. we could provide a commented line in the `Podfile` template that explicitly includes the pod only in debug configurations _before_ auto-linking, as both documentation and as a hint to the ability to create flipper plugins.

Anyways, just my 2 cents.

**Comment by martinezguillaume** [comment]
Sorry to bother you guys but the goal here is not build Flipper in Release right ?
Because if we’re building it but not includes it, we still have a long build time (it takes me nearly 1 hour in bitrise to build)

**Comment by alloy** [comment]
@martinezguillaume This issue is about  dependencies being _linked_ to the app in release mode when not expecting that, not about build time.

**Comment by mweststrate** [comment]
@martinezguillaume I assume it is not Flipper itself that takes the one hour to build? For an empty React Native project it takes me 1.5 minutes to build a release with a cleared cache, and it's basically instant on a rebuild. So I don't think all that time is imposed by Flipper? If you have an hour without Flipper already, that doesn't feel like not building those Flipper libs are the biggest win you can make :)

**Comment by martinezguillaume** [comment]
I can’t build without building Flipper for the moment, that’s why I’m searching for a solution. But I can assure you that flipper take a huge building time (example here https://github.com/react-native-community/discussions-and-proposals/issues/226)

**Comment by mweststrate** [comment]
@martinezguillaume I think it is best to open a new issue, you are now touching two problems that are not the subject of this issue: 1) Flipper seemingly making your build slow, and 2) not being able to build without Flipper. This issue is about having Flipper code ending up in release artifacts which is a maybe related but a different problem.

**Comment by lfalkner** [comment]
@mweststrate How do we specify which version of flipper RN 62.2 is using? Must we still disable auto link and import the pod per [the workaround here](https://github.com/facebook/flipper/issues/976#issuecomment-612874193)

**Comment by mweststrate** [comment]
@lfalkner this issue is closed, please open a fresh one with full detail of the podfile, dependencies in package.json etc.

**Comment by badredaha** [comment]
The same Problem here !

**Comment by mweststrate** [comment]
As stated in a few issues now, flipper will be part of the build but not linked when building a release, so they won't end up in the product. If you don't want Flipper _at all_, it is straightforward to disable it as described [here](https://github.com/facebook/flipper/issues/1275#issuecomment-659386608). But unless someone knows a way to make the build infra smarter, there isn't much we can do beyond that and make it build only in dev builds. So there is no point in adding more reports that builds are slow, as that is not something we can influence at this point. Obviously, if anybody has ideas how to make this smarter within the iOS eco system, without introducing other risks, PRs are welcome.
